; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common_env_settings]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_mode = opi
board_upload.flash_size = 8MB
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    lovyan03/LovyanGFX
    sparkfun/SparkFun VL53L5CX Arduino Library
    ;https://github.com/SMLOWE/QMI8658.git
board_build.filesystem = littlefs
src_filter = +<*>

build_flags =
    -DUSE_HSPI_PORT
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Ofast
    -DUSER_SETUP_LOADED=1
    -DTOUCH_CS=48
    -DSPI_FREQUENCY=80000000
    -DSPI_TOUCH_FREQUENCY=2500000
    -D HAS_OLED
    -D HAS_TOF
    -DTOF_LPN=17
    -DTOF_INT=-1
    -DI2C_SDA=18
    -DI2C_SCL=8
    

[env:ili9341]
extends = common_env_settings
build_flags =
    ${common_env_settings.build_flags}
    -DSCREEN_ILI9341
    -DILI9341_DRIVER=1
    -DTFT_MISO=9
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=47
    -DTFT_DC=13
    -DTFT_RST=14
    -DTFT_BL=46

[env:gc9a01_dual]
extends = common_env_settings
build_flags =
    ${common_env_settings.build_flags}
    -DSCREEN_GC9A01_DUAL
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_MISO=9
    -DTFT_CS=-1
    -DTFT_DC=13
    -DTFT_RST=14
    -DTFT_CS_L=10
    -DTFT_CS_R=21

[env:gc9a01]
extends = common_env_settings
build_flags =
    ${common_env_settings.build_flags}
    -DSCREEN_GC9A01
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=13
    -DTFT_RST=14